-- Schema Perú. Mismo núcleo que Chile, sin LinkedIn ni inscripciones a eventos.
-- El catálogo de Aplicaciones vive en shared.applications
-- (supabase/shared/schema.sql); peru.applications es una vista.

CREATE SCHEMA IF NOT EXISTS peru;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intranet_peru') THEN
    CREATE ROLE intranet_peru LOGIN NOINHERIT;
  END IF;
END$$;

ALTER ROLE intranet_peru BYPASSRLS;
ALTER ROLE intranet_peru SET search_path = peru;

REVOKE ALL ON SCHEMA peru FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA peru TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON SCHEMA peru FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON SCHEMA peru FROM authenticated;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intranet_chile') THEN
    REVOKE ALL ON SCHEMA peru FROM intranet_chile;
  END IF;
END$$;

-- Enum vacaciones (por schema: el mismo typname en chile y peru no choca)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'vacation_request_status'
      AND n.nspname = 'peru'
  ) THEN
    CREATE TYPE peru.vacation_request_status AS ENUM (
      'pending', 'approved', 'rejected', 'cancelled', 'in_progress', 'completed'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS peru.work_areas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_name character varying(150) NOT NULL,
  color character varying(7) NOT NULL DEFAULT '#5a6879',
  -- Jefe del área: primera aprobación del centro de gastos. La FK hacia users
  -- se agrega más abajo, porque esa tabla se crea después de esta.
  manager_user_id integer,
  CONSTRAINT work_areas_area_name_key UNIQUE (area_name),
  CONSTRAINT work_areas_color_hex CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE IF NOT EXISTS peru.users (
  id integer PRIMARY KEY,
  first_name character varying(100),
  last_name character varying(100),
  email character varying(150),
  password_hash character varying(255),
  password_salt character varying(255),
  role character varying(50),
  email_confirmed boolean DEFAULT false,
  confirm_token character varying(255),
  confirm_expires timestamp without time zone,
  photo text,
  created_at timestamp without time zone DEFAULT now(),
  must_change_password boolean DEFAULT false,
  work_area_id integer REFERENCES peru.work_areas(id),
  birth_date date,
  is_intranet_user boolean NOT NULL DEFAULT true,
  -- Celular personal: lo ingresa la persona al registrarse o en su perfil.
  phone numeric,
  -- Contacto de empresa vs. personal: `email` es el corporativo (login) y
  -- `work_phone` el celular de la empresa. Sólo esos dos se muestran en el
  -- directorio y los entrega el asistente; los personales quedan ocultos.
  personal_email character varying(150),
  work_phone numeric,
  home_tutorial_seen boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  hire_date date,
  manager_user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  prior_years_credited numeric(4,1) NOT NULL DEFAULT 0,
  progressive_days_override numeric(4,1),
  work_days_per_week smallint NOT NULL DEFAULT 5
    CHECK (work_days_per_week BETWEEN 3 AND 6),
  -- Documento de identidad: RUT en Chile, DNI en Perú. La forma la valida
  -- utils/nationalId.js según config/country.js. Admite NULL porque los
  -- colaboradores ya cargados no lo tienen; la rendición de gastos sí lo exige.
  national_id character varying(20),
  CONSTRAINT users_email_key UNIQUE (email)
);
-- Único parcial: dos personas no comparten documento, pero muchas lo tienen
-- vacío todavía.
CREATE UNIQUE INDEX IF NOT EXISTS users_national_id_unique_idx
  ON peru.users (national_id) WHERE national_id IS NOT NULL;

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = con.connamespace
    WHERE con.conname = 'work_areas_manager_fk'
      AND c.relname = 'work_areas' AND n.nspname = 'peru'
  ) THEN
    ALTER TABLE peru.work_areas
      ADD CONSTRAINT work_areas_manager_fk
      FOREIGN KEY (manager_user_id) REFERENCES peru.users(id) ON DELETE SET NULL;
  END IF;
END
$do$;
CREATE INDEX IF NOT EXISTS idx_work_areas_manager
  ON peru.work_areas (manager_user_id) WHERE manager_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx
  ON peru.users (LOWER(TRIM(email)))
  WHERE email IS NOT NULL AND TRIM(email) <> '';

CREATE INDEX IF NOT EXISTS idx_users_hire_date ON peru.users (hire_date) WHERE hire_date IS NOT NULL;

-- Instancias creadas antes de separar el contacto de empresa del personal.
ALTER TABLE peru.users ADD COLUMN IF NOT EXISTS personal_email character varying(150);
ALTER TABLE peru.users ADD COLUMN IF NOT EXISTS work_phone numeric;

-- Catálogo corporativo: tabla en shared.applications (supabase/shared/schema.sql).
CREATE OR REPLACE VIEW peru.applications
  WITH (security_invoker = true) AS
  SELECT * FROM shared.applications;
GRANT SELECT, INSERT, UPDATE, DELETE ON peru.applications TO intranet_peru;

-- Asistente: historial, cupo diario y aviso de límites por persona.
CREATE TABLE IF NOT EXISTS peru.claude_conversations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES peru.users(id) ON DELETE CASCADE,
  title character varying(255) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_claude_conversations_user_id
  ON peru.claude_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_claude_conversations_updated_at
  ON peru.claude_conversations (updated_at DESC);

CREATE TABLE IF NOT EXISTS peru.claude_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id integer NOT NULL REFERENCES peru.claude_conversations(id) ON DELETE CASCADE,
  role character varying(20) NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_claude_messages_conversation_id
  ON peru.claude_messages (conversation_id);

CREATE TABLE IF NOT EXISTS peru.claude_daily_usage (
  user_id integer NOT NULL REFERENCES peru.users(id) ON DELETE CASCADE,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  message_count integer NOT NULL DEFAULT 0 CHECK (message_count >= 0),
  file_count integer NOT NULL DEFAULT 0 CHECK (file_count >= 0),
  PRIMARY KEY (user_id, usage_date)
);

CREATE TABLE IF NOT EXISTS peru.claude_user_settings (
  user_id integer PRIMARY KEY REFERENCES peru.users(id) ON DELETE CASCADE,
  limits_notice_seen_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS peru.change_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  action character varying(255),
  section character varying(100),
  link_path text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS peru.courses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title character varying(255) NOT NULL,
  description text,
  material_url text,
  video_url text NOT NULL,
  required_watch_seconds integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  commercial_tips text,
  section character varying(255),
  subsection character varying(255)
);

CREATE TABLE IF NOT EXISTS peru.documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(200) NOT NULL,
  -- Forma histórica del tipo ('procedimiento_logistica'). Se sigue escribiendo
  -- por compatibilidad, pero la navegación usa work_area_id + doc_kind.
  type character varying(50) NOT NULL,
  url text NOT NULL,
  public_id character varying(100),
  user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  created_at timestamp without time zone DEFAULT now(),
  -- La carpeta de procedimientos y protocolos muere con el área. Los objetos
  -- del bucket no tienen FK: los borra la ruta de eliminación de áreas.
  work_area_id integer REFERENCES peru.work_areas(id) ON DELETE CASCADE,
  doc_kind character varying(20)
);
CREATE INDEX IF NOT EXISTS idx_documents_area_kind
  ON peru.documents (work_area_id, doc_kind);

-- ===========================================================
-- CENTROS DE COSTO
-- Segunda agrupación de colaboradores, independiente del área: el área dice
-- quién aprueba (una sola por persona) y el centro de costo a qué bolsillo se
-- carga el gasto (hasta dos por persona).
-- ===========================================================
CREATE TABLE IF NOT EXISTS peru.cost_centers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- El código es lo que cita contabilidad: es la clave natural.
  code character varying(30) NOT NULL,
  name character varying(150) NOT NULL,
  -- Un centro en desuso se desactiva, no se borra: las rendiciones históricas
  -- tienen que seguir apuntando a algo.
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS cost_centers_code_unique_idx
  ON peru.cost_centers (UPPER(TRIM(code)));
CREATE INDEX IF NOT EXISTS idx_cost_centers_active
  ON peru.cost_centers (active) WHERE active = true;

-- El tope de dos centros por colaborador se aplica en la ruta
-- (services/costCenters/costCenterService.js), no aquí: expresarlo en SQL
-- exigiría un trigger, y el único camino de escritura es /RRHH/centros-costo.
CREATE TABLE IF NOT EXISTS peru.user_cost_centers (
  user_id integer NOT NULL REFERENCES peru.users(id) ON DELETE CASCADE,
  cost_center_id integer NOT NULL REFERENCES peru.cost_centers(id) ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, cost_center_id)
);
CREATE INDEX IF NOT EXISTS idx_user_cost_centers_center
  ON peru.user_cost_centers (cost_center_id);

-- ===========================================================
-- BANCOS Y CUENTAS DE DESTINO
-- PK = código de la institución. Perú aún no tiene filas: con la tabla
-- vacía el formulario no pide cuenta. El catálogo vivo es esta tabla.
-- ===========================================================
CREATE TABLE IF NOT EXISTS peru.banks (
  code character varying(3) PRIMARY KEY,
  name character varying(120) NOT NULL,
  entity_type character varying(40) NOT NULL,
  active boolean NOT NULL DEFAULT true
);

-- Cuentas propias guardadas. Sin id: la clave es la cuenta misma.
CREATE TABLE IF NOT EXISTS peru.user_bank_accounts (
  user_id integer NOT NULL REFERENCES peru.users(id) ON DELETE CASCADE,
  bank_code character varying(3) NOT NULL REFERENCES peru.banks(code) ON UPDATE CASCADE,
  account_type character varying(20) NOT NULL,
  account_number character varying(20) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone,
  PRIMARY KEY (user_id, bank_code, account_type, account_number)
);

-- ===========================================================
-- CENTRO DE GASTOS
-- Dos etapas: el jefe del área aprueba y después Finanzas.
-- ===========================================================
DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'expense_request_kind' AND n.nspname = 'peru'
  ) THEN
    CREATE TYPE peru.expense_request_kind AS ENUM ('rendicion','fondos');
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'expense_request_status' AND n.nspname = 'peru'
  ) THEN
    CREATE TYPE peru.expense_request_status AS ENUM
      ('pending','approved_manager','approved_finance','rejected','cancelled','draft');
  END IF;
END
$do$;
-- Bases creadas antes de los borradores.
ALTER TYPE peru.expense_request_status ADD VALUE IF NOT EXISTS 'draft';

CREATE TABLE IF NOT EXISTS peru.expense_requests (
  id integer PRIMARY KEY,                        -- 8 dígitos (trg_eight_digit_id)
  kind peru.expense_request_kind NOT NULL,
  status peru.expense_request_status NOT NULL DEFAULT 'pending',
  -- Borrar al colaborador no borra sus solicitudes: quedan con la ficha
  -- congelada (requester_*) y user_id NULL.
  user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  -- Se congela al crear: si el colaborador cambia de área, la solicitud sigue
  -- perteneciendo al área que la aprobó.
  work_area_id integer REFERENCES peru.work_areas(id) ON DELETE SET NULL,
  title character varying(200) NOT NULL,
  description text,
  currency_code character varying(3) NOT NULL,
  -- Siempre recalculado en el servidor desde expense_request_items.
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  needed_by date,                                -- sólo kind = 'fondos'
  -- Aprobador esperado. NULL con status 'pending' significa que el solicitante
  -- ES el jefe del área: no puede autoaprobarse y lo resuelve un administrador.
  manager_user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  manager_reviewed_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  manager_reviewed_at timestamp with time zone,
  manager_notes text,
  finance_reviewed_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  finance_reviewed_at timestamp with time zone,
  finance_notes text,
  rejected_stage character varying(10),          -- 'manager' | 'finance'
  -- Datos del solicitante congelados al enviar. Una rendición es un documento
  -- contable: si mañana se corrige un RUT o alguien cambia de área, lo que
  -- Finanzas ya aprobó no debe cambiar solo.
  requester_name character varying(200),
  requester_national_id character varying(20),
  requester_email character varying(150),
  requester_area_name character varying(150),
  -- Imputación. El FK sirve para filtrar y agrupar; el código y el nombre se
  -- congelan por la misma razón que los datos del solicitante.
  cost_center_id integer REFERENCES peru.cost_centers(id) ON DELETE SET NULL,
  cost_center_code character varying(30),
  cost_center_name character varying(150),
  -- Cuenta de destino congelada al enviar. El titular son los requester_*.
  bank_code character varying(3) REFERENCES peru.banks(code) ON UPDATE CASCADE,
  bank_name character varying(120),
  bank_account_type character varying(20),
  bank_account_number character varying(20),
  -- Encabezado de la planilla de rendición.
  destination character varying(150),
  period_start date,
  period_end date,
  -- Fondo asignado: lo copia el sistema del total de la solicitud de fondos
  -- que se rinde (NULL = reembolso). Saldo = total_amount - assigned_amount.
  assigned_amount numeric(14,2)
    CHECK (assigned_amount IS NULL OR assigned_amount >= 0),
  -- Solicitud de fondos que esta rendición rinde (1:1). NULL = reembolso.
  -- NO ACTION: nada borra una solicitud de fondos enviada (ni borrar al usuario).
  fund_request_id integer REFERENCES peru.expense_requests(id),
  -- Liquidación: Finanzas confirma la devolución o el pago del saldo.
  settled_at timestamp with time zone,
  settled_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  settlement_notes text,
  CONSTRAINT expense_requests_fund_request_kind
    CHECK (fund_request_id IS NULL OR kind = 'rendicion'),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_expense_requests_cost_center
  ON peru.expense_requests (cost_center_id, status);
CREATE INDEX IF NOT EXISTS idx_expense_requests_user
  ON peru.expense_requests (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expense_requests_status
  ON peru.expense_requests (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expense_requests_area
  ON peru.expense_requests (work_area_id, status);
-- La bandeja del jefe es exactamente esta consulta.
CREATE INDEX IF NOT EXISTS idx_expense_requests_manager
  ON peru.expense_requests (manager_user_id, status)
  WHERE manager_user_id IS NOT NULL;
-- Borradores caducados (se eliminan a los 30 días sin cambios).
CREATE INDEX IF NOT EXISTS idx_expense_requests_drafts
  ON peru.expense_requests (updated_at)
  WHERE status = 'draft';
-- 1:1 fondo ↔ rendición: un fondo no puede tener dos rendiciones en curso o aprobadas.
CREATE UNIQUE INDEX IF NOT EXISTS expense_requests_fund_rendicion_unique
  ON peru.expense_requests (fund_request_id)
  WHERE kind = 'rendicion' AND status IN ('pending', 'approved_manager', 'approved_finance');
CREATE INDEX IF NOT EXISTS idx_expense_requests_fund
  ON peru.expense_requests (fund_request_id)
  WHERE fund_request_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS peru.expense_request_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id integer NOT NULL REFERENCES peru.expense_requests(id) ON DELETE CASCADE,
  item_date date,
  category character varying(30),                -- constants/expenseCategories.js
  days smallint CHECK (days IS NULL OR days > 0), -- sólo category = 'hospedaje'
  details jsonb,                                  -- extra de combustible (km/L, km, $/L)
  detail character varying(300) NOT NULL,
  amount numeric(14,2) CHECK (amount >= 0),       -- NULL sólo en borradores
  sort_order smallint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_expense_items_request
  ON peru.expense_request_items (request_id, sort_order);

CREATE TABLE IF NOT EXISTS peru.expense_request_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id integer NOT NULL REFERENCES peru.expense_requests(id) ON DELETE CASCADE,
  item_id bigint REFERENCES peru.expense_request_items(id) ON DELETE SET NULL,
  name character varying(200) NOT NULL,
  url text NOT NULL,
  public_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_expense_attachments_request
  ON peru.expense_request_attachments (request_id);
CREATE INDEX IF NOT EXISTS idx_expense_attachments_item
  ON peru.expense_request_attachments (item_id)
  WHERE item_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS peru.events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(200) NOT NULL,
  slug character varying(200) NOT NULL UNIQUE,
  description text,
  image text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS peru.lunch_menu (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_number integer NOT NULL UNIQUE,
  dish_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS peru.news_articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title character varying(255) NOT NULL,
  subtitle character varying(255),
  content text NOT NULL,
  image text,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  slug character varying(100),
  author character varying(100),
  featured boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_news_articles_featured
  ON peru.news_articles (featured) WHERE featured = true;

CREATE TABLE IF NOT EXISTS peru.other_documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL,
  public_id text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS peru.public_holidays (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  holiday_date date NOT NULL,
  name character varying(200) NOT NULL,
  is_recurring boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (country_code, holiday_date)
);
CREATE INDEX IF NOT EXISTS idx_public_holidays_country_date
  ON peru.public_holidays (country_code, holiday_date);

CREATE TABLE IF NOT EXISTS peru.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer REFERENCES peru.courses(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  sort_order integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  feedback text
);

CREATE TABLE IF NOT EXISTS peru.question_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint REFERENCES peru.questions(id) ON DELETE CASCADE,
  text text NOT NULL,
  is_correct boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS peru.study_materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section character varying(255) NOT NULL,
  name character varying(255) NOT NULL,
  file_url text NOT NULL,
  public_id character varying(255) NOT NULL,
  resource_type character varying(50) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS peru.subsection_details (
  name character varying(255) PRIMARY KEY,
  image_url text
);

CREATE TABLE IF NOT EXISTS peru.support_tickets (
  id integer PRIMARY KEY,
  title character varying(200) NOT NULL,
  description text NOT NULL,
  category character varying(100),
  priority character varying(50),
  status character varying(50) DEFAULT 'Abierto',
  requester_name character varying(150),
  requester_email character varying(150),
  created_at timestamp without time zone DEFAULT now(),
  resolved_at timestamp without time zone,
  closed_at timestamp without time zone,
  auto_closed boolean DEFAULT false,
  attachments text DEFAULT '[]',
  read_by_user boolean DEFAULT true,
  read_by_admin boolean DEFAULT true,
  assigned_to character varying(255)
);

CREATE TABLE IF NOT EXISTS peru.system_config (
  key text PRIMARY KEY,
  value text,
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS peru.ticket_replies (
  id integer NOT NULL,
  ticket_id integer NOT NULL REFERENCES peru.support_tickets(id) ON DELETE CASCADE,
  message text NOT NULL,
  sender character varying(150),
  file_url text,
  file_name text,
  file_type text,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  PRIMARY KEY (ticket_id, id)
);

CREATE TABLE IF NOT EXISTS peru.user_course_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES peru.users(id) ON DELETE CASCADE,
  course_id integer REFERENCES peru.courses(id) ON DELETE CASCADE,
  seconds_watched integer DEFAULT 0,
  status character varying(50) DEFAULT 'en_progreso',
  score numeric(5,2),
  started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp without time zone,
  attempts integer DEFAULT 0,
  UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS peru.vacation_periods (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Borrar al colaborador conserva sus períodos (y sus ajustes): user_id NULL.
  user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  period_start date NOT NULL,
  period_end date NOT NULL,
  entitled_days numeric(5,2) NOT NULL,
  used_days numeric(5,2) NOT NULL DEFAULT 0,
  adjusted_days numeric(5,2) NOT NULL DEFAULT 0,
  expires_at date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  protected_block_days_used numeric(5,2) NOT NULL DEFAULT 0,
  flexible_block_days_used numeric(5,2) NOT NULL DEFAULT 0,
  record_met boolean NOT NULL DEFAULT true,
  record_validated_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  record_notes text,
  UNIQUE (user_id, period_start)
);
CREATE INDEX IF NOT EXISTS idx_vacation_periods_user ON peru.vacation_periods (user_id);

CREATE TABLE IF NOT EXISTS peru.vacation_requests (
  id integer PRIMARY KEY,
  -- Borrar al colaborador conserva sus solicitudes: user_id NULL y la ficha
  -- queda en requester_*.
  user_id integer REFERENCES peru.users(id) ON DELETE SET NULL,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  vacation_period_id integer REFERENCES peru.vacation_periods(id) ON DELETE SET NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  business_days numeric(5,2),
  calendar_days integer,
  status peru.vacation_request_status NOT NULL DEFAULT 'pending',
  requester_notes text,
  reviewer_notes text,
  reviewed_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  fraction_ack_at timestamp with time zone,
  policy_warning_ack boolean NOT NULL DEFAULT false,
  period_allocations jsonb,
  -- Ficha del solicitante copiada al crear la solicitud.
  requester_first_name character varying(150),
  requester_last_name character varying(150),
  requester_email character varying(150),
  requester_area_name character varying(150),
  CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_user ON peru.vacation_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON peru.vacation_requests (status);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON peru.vacation_requests (start_date, end_date);

CREATE TABLE IF NOT EXISTS peru.vacation_balance_adjustments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vacation_period_id integer NOT NULL REFERENCES peru.vacation_periods(id) ON DELETE CASCADE,
  adjusted_by integer REFERENCES peru.users(id) ON DELETE SET NULL,
  days_delta numeric(5,2) NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vacation_balance_adjustments_period
  ON peru.vacation_balance_adjustments (vacation_period_id);

CREATE OR REPLACE FUNCTION peru.marcar_recuperacion_pass(
  email_input text,
  nuevo_password_hash text
)
RETURNS void
LANGUAGE plpgsql
SET search_path = peru
AS $function$
BEGIN
  UPDATE peru.users
  SET password_hash = nuevo_password_hash,
      must_change_password = TRUE
  WHERE LOWER(email) = LOWER(email_input);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Usuario con email % no encontrado', email_input;
  END IF;
END;
$function$;

-- RLS activo. intranet_peru tiene BYPASSRLS. Policies: dashboard vs PostgREST.
ALTER TABLE peru.change_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.claude_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.claude_daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.claude_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.claude_user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.user_cost_centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.expense_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.expense_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.expense_request_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.user_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.lunch_menu ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.news_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.other_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.public_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.question_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.study_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.subsection_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.ticket_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.user_course_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.vacation_balance_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.vacation_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.vacation_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE peru.work_areas ENABLE ROW LEVEL SECURITY;

GRANT USAGE, CREATE ON SCHEMA peru TO intranet_peru;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA peru TO intranet_peru;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA peru TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.marcar_recuperacion_pass(text, text) TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT USAGE ON SCHEMA peru TO service_role;
    GRANT ALL ON ALL TABLES IN SCHEMA peru TO service_role;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA peru TO service_role;
    GRANT EXECUTE ON FUNCTION peru.marcar_recuperacion_pass(text, text) TO service_role;
  END IF;
END$$;

DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relkind = 'r'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS dashboard_all ON peru.%I', r.relname);
    EXECUTE format(
      'CREATE POLICY dashboard_all ON peru.%I FOR ALL TO postgres USING (true) WITH CHECK (true)',
      r.relname
    );
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
       AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      EXECUTE format('DROP POLICY IF EXISTS deny_postgrest ON peru.%I', r.relname);
      EXECUTE format(
        'CREATE POLICY deny_postgrest ON peru.%I FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)',
        r.relname
      );
    END IF;
  END LOOP;
END$$;

-- IDs: 6 dígitos aleatorios (100000-999999) en users y vacation_requests.
-- 8 dígitos aleatorios (10000000-99999999) en expense_requests (fondos y rendiciones).
-- 4 dígitos aleatorios (1111-9999) en work_areas y support_tickets.
-- integer IDENTITY en catálogo (noticias, eventos, apps, cursos, períodos,
-- documentos, feriados, menú, fotos, linkedin, progreso).
-- bigint IDENTITY en academy/quiz y logs (questions, question_options,
-- change_log). ticket_replies usa correlativo 1, 2, 3… por ticket.
-- ensure_id_strategy remapea filas existentes, propaga FKs/JSON/paths y deja
-- trigger o IDENTITY. No llamar en cada arranque de Node: toma ACCESS EXCLUSIVE
-- en todo el schema.

CREATE OR REPLACE FUNCTION peru.next_six_digit_id(p_table text)
RETURNS integer
LANGUAGE plpgsql
AS $fn$
DECLARE
  candidate integer;
  found_id integer;
  i integer;
BEGIN
  IF p_table IS NULL OR p_table !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'tabla inválida para ID de 6 dígitos';
  END IF;
  FOR i IN 1..80 LOOP
    candidate := 100000 + floor(random() * 900000)::integer;
    found_id := NULL;
    EXECUTE format('SELECT 1 FROM peru.%I WHERE id = $1', p_table)
      INTO found_id
      USING candidate;
    IF found_id IS NULL THEN
      RETURN candidate;
    END IF;
  END LOOP;
  RAISE EXCEPTION 'No fue posible generar un ID de 6 dígitos para peru.%', p_table;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.assign_six_digit_id()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.id IS NULL OR NEW.id < 100000 THEN
    NEW.id := peru.next_six_digit_id(TG_TABLE_NAME);
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.next_eight_digit_id(p_table text)
RETURNS integer
LANGUAGE plpgsql
AS $fn$
DECLARE
  candidate integer;
  found_id integer;
  i integer;
BEGIN
  IF p_table IS NULL OR p_table !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'tabla inválida para ID de 8 dígitos';
  END IF;
  FOR i IN 1..80 LOOP
    candidate := 10000000 + floor(random() * 90000000)::integer;
    found_id := NULL;
    EXECUTE format('SELECT 1 FROM peru.%I WHERE id = $1', p_table)
      INTO found_id
      USING candidate;
    IF found_id IS NULL THEN
      RETURN candidate;
    END IF;
  END LOOP;
  RAISE EXCEPTION 'No fue posible generar un ID de 8 dígitos para peru.%', p_table;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.assign_eight_digit_id()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.id IS NULL OR NEW.id < 10000000 THEN
    NEW.id := peru.next_eight_digit_id(TG_TABLE_NAME);
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.next_four_digit_id(p_table text)
RETURNS integer
LANGUAGE plpgsql
AS $fn$
DECLARE
  candidate integer;
  found_id integer;
  i integer;
BEGIN
  IF p_table IS NULL OR p_table !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'tabla inválida para ID de 4 dígitos';
  END IF;
  FOR i IN 1..80 LOOP
    candidate := 1111 + floor(random() * 8889)::integer;
    found_id := NULL;
    EXECUTE format('SELECT 1 FROM peru.%I WHERE id = $1', p_table)
      INTO found_id
      USING candidate;
    IF found_id IS NULL THEN
      RETURN candidate;
    END IF;
  END LOOP;
  RAISE EXCEPTION 'No fue posible generar un ID de 4 dígitos para peru.%', p_table;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.assign_four_digit_id()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.id IS NULL OR NEW.id < 1111 OR NEW.id > 9999 THEN
    NEW.id := peru.next_four_digit_id(TG_TABLE_NAME);
  END IF;
  RETURN NEW;
END;
$fn$;

-- Correlativo 1, 2, 3… por ticket (no un identity global).
CREATE OR REPLACE FUNCTION peru.assign_ticket_reply_id()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.ticket_id IS NULL THEN
    RAISE EXCEPTION 'ticket_id es obligatorio';
  END IF;
  PERFORM 1 FROM peru.support_tickets WHERE id = NEW.ticket_id FOR UPDATE;
  IF NEW.id IS NULL OR NEW.id <= 0 THEN
    SELECT COALESCE(MAX(id), 0) + 1
      INTO NEW.id
      FROM peru.ticket_replies
     WHERE ticket_id = NEW.ticket_id;
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS trg_ticket_reply_id ON peru.ticket_replies;
CREATE TRIGGER trg_ticket_reply_id
  BEFORE INSERT ON peru.ticket_replies
  FOR EACH ROW EXECUTE FUNCTION peru.assign_ticket_reply_id();

CREATE OR REPLACE FUNCTION peru.ensure_id_strategy()
RETURNS void
LANGUAGE plpgsql
AS $fn$
DECLARE
  p_schema constant text := 'peru';
  p_role constant text := 'intranet_peru';
  staging_offset constant bigint := 2000000000;
  six_digit_tables constant text[] := ARRAY[
    'users', 'vacation_requests'
  ];
  eight_digit_tables constant text[] := ARRAY[
    'expense_requests'
  ];
  four_digit_tables constant text[] := ARRAY[
    'work_areas', 'support_tickets'
  ];
  identity_tables constant text[] := ARRAY[
    'news_articles', 'events', 'courses', 'vacation_periods',
    'vacation_balance_adjustments',
    'lunch_menu', 'public_holidays', 'documents', 'other_documents',
    'study_materials', 'linkedin_posts', 'user_course_progress',
    'expense_request_items', 'expense_request_attachments', 'cost_centers',
    'claude_conversations'
  ];
  bigint_identity_tables constant text[] := ARRAY[
    'questions', 'question_options', 'change_log', 'claude_messages'
  ];
  sequential_tables text[];
  t record;
  r record;
  rec record;
  fk record;
  tname text;
  candidate bigint;
  found_id bigint;
  i integer;
  seq_name text;
  max_id bigint;
  has_created_at boolean;
  table_ok boolean;
  ident text;
  order_sql text;
BEGIN
  sequential_tables := identity_tables || bigint_identity_tables;

  FOR t IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema AND c.relkind = 'r'
  LOOP
    EXECUTE format('LOCK TABLE %I.%I IN ACCESS EXCLUSIVE MODE', p_schema, t.relname);
  END LOOP;

  DROP TABLE IF EXISTS _id_map;
  DROP TABLE IF EXISTS _fk_backup;
  CREATE TEMP TABLE _id_map (
    table_name text NOT NULL,
    old_id bigint NOT NULL,
    new_id bigint NOT NULL,
    PRIMARY KEY (table_name, old_id),
    UNIQUE (table_name, new_id)
  ) ON COMMIT DROP;
  CREATE TEMP TABLE _fk_backup (
    table_name text NOT NULL,
    conname text NOT NULL,
    def text NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO _fk_backup (table_name, conname, def)
  SELECT c.relname, con.conname, pg_get_constraintdef(con.oid)
  FROM pg_constraint con
  JOIN pg_class c ON c.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = con.connamespace
  WHERE con.contype = 'f' AND n.nspname = p_schema;

  FOR fk IN SELECT * FROM _fk_backup LOOP
    EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', p_schema, fk.table_name, fk.conname);
  END LOOP;

  FOREACH tname IN ARRAY four_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    FOR rec IN EXECUTE format(
      'SELECT id FROM %I.%I WHERE id < 1111 OR id > 9999 ORDER BY id',
      p_schema, tname
    ) LOOP
      FOR i IN 1..80 LOOP
        candidate := 1111 + floor(random() * 8889)::integer;
        found_id := NULL;
        EXECUTE format('SELECT 1 FROM %I.%I WHERE id = $1', p_schema, tname)
          INTO found_id
          USING candidate;
        EXIT WHEN found_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM _id_map m
            WHERE m.table_name = tname AND m.new_id = candidate
          );
        IF i = 80 THEN
          RAISE EXCEPTION 'No fue posible generar un ID de 4 dígitos para %.%', p_schema, tname;
        END IF;
      END LOOP;
      INSERT INTO _id_map (table_name, old_id, new_id)
      VALUES (tname, rec.id, candidate);
    END LOOP;
  END LOOP;

  FOREACH tname IN ARRAY six_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    FOR rec IN EXECUTE format(
      'SELECT id FROM %I.%I WHERE id < 100000 ORDER BY id',
      p_schema, tname
    ) LOOP
      FOR i IN 1..80 LOOP
        candidate := 100000 + floor(random() * 900000)::integer;
        found_id := NULL;
        EXECUTE format('SELECT 1 FROM %I.%I WHERE id = $1', p_schema, tname)
          INTO found_id
          USING candidate;
        EXIT WHEN found_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM _id_map m
            WHERE m.table_name = tname AND m.new_id = candidate
          );
        IF i = 80 THEN
          RAISE EXCEPTION 'No fue posible generar un ID de 6 dígitos para %.%', p_schema, tname;
        END IF;
      END LOOP;
      INSERT INTO _id_map (table_name, old_id, new_id)
      VALUES (tname, rec.id, candidate);
    END LOOP;
  END LOOP;

  FOREACH tname IN ARRAY eight_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    FOR rec IN EXECUTE format(
      'SELECT id FROM %I.%I WHERE id < 10000000 ORDER BY id',
      p_schema, tname
    ) LOOP
      FOR i IN 1..80 LOOP
        candidate := 10000000 + floor(random() * 90000000)::integer;
        found_id := NULL;
        EXECUTE format('SELECT 1 FROM %I.%I WHERE id = $1', p_schema, tname)
          INTO found_id
          USING candidate;
        EXIT WHEN found_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM _id_map m
            WHERE m.table_name = tname AND m.new_id = candidate
          );
        IF i = 80 THEN
          RAISE EXCEPTION 'No fue posible generar un ID de 8 dígitos para %.%', p_schema, tname;
        END IF;
      END LOOP;
      INSERT INTO _id_map (table_name, old_id, new_id)
      VALUES (tname, rec.id, candidate);
    END LOOP;
  END LOOP;

  FOREACH tname IN ARRAY sequential_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I', p_schema, tname) INTO max_id;
    IF max_id < 100000 THEN
      CONTINUE;
    END IF;

    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = p_schema AND table_name = tname AND column_name = 'created_at'
    ) INTO has_created_at;
    order_sql := CASE WHEN has_created_at THEN 'created_at, id' ELSE 'id' END;

    EXECUTE
      'INSERT INTO _id_map (table_name, old_id, new_id)
       SELECT $1, s.id, s.rn
       FROM (
         SELECT id, row_number() OVER (ORDER BY ' || order_sql || ')::bigint AS rn
         FROM ' || quote_ident(p_schema) || '.' || quote_ident(tname) || '
       ) s
       WHERE s.id IS DISTINCT FROM s.rn'
      USING tname;
  END LOOP;

  FOR r IN
    SELECT
      b.table_name AS child_table,
      (regexp_match(b.def, 'FOREIGN KEY \(([a-z0-9_]+)\)'))[1] AS fk_col,
      (regexp_match(b.def, 'REFERENCES (?:[a-z_]+\.)?([a-z0-9_]+)\(id\)'))[1] AS parent_table
    FROM _fk_backup b
  LOOP
    IF r.fk_col IS NULL OR r.parent_table IS NULL THEN
      CONTINUE;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM _id_map m WHERE m.table_name = r.parent_table
    ) THEN
      CONTINUE;
    END IF;
    EXECUTE format(
      'UPDATE %I.%I t SET %I = m.new_id FROM _id_map m WHERE m.table_name = %L AND t.%I = m.old_id',
      p_schema, r.child_table, r.fk_col, r.parent_table, r.fk_col
    );
  END LOOP;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = p_schema
      AND table_name = 'vacation_requests'
      AND column_name = 'period_allocations'
  ) THEN
    EXECUTE format(
      $q$
      UPDATE %I.vacation_requests vr
      SET period_allocations = sub.new_alloc
      FROM (
        SELECT vr2.id,
          jsonb_agg(
            CASE
              WHEN m.new_id IS NULL THEN elem
              ELSE jsonb_set(elem, '{periodId}', to_jsonb(m.new_id))
            END
            ORDER BY ordinality
          ) AS new_alloc
        FROM %I.vacation_requests vr2
        CROSS JOIN LATERAL jsonb_array_elements(vr2.period_allocations)
          WITH ORDINALITY AS x(elem, ordinality)
        LEFT JOIN _id_map m
          ON m.table_name = 'vacation_periods'
         AND m.old_id = NULLIF(elem->>'periodId', '')::bigint
        WHERE vr2.period_allocations IS NOT NULL
          AND jsonb_typeof(vr2.period_allocations) = 'array'
          AND jsonb_array_length(vr2.period_allocations) > 0
        GROUP BY vr2.id
      ) sub
      WHERE vr.id = sub.id
      $q$,
      p_schema, p_schema
    );
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = 'change_log'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = p_schema AND table_name = 'change_log' AND column_name = 'link_path'
  ) THEN
    EXECUTE format(
      $q$
      UPDATE %I.change_log cl
      SET link_path = regexp_replace(
        cl.link_path,
        '/(' || m.old_id::text || ')(/|\?|$)',
        '/' || m.new_id::text || '\2',
        'g'
      )
      FROM _id_map m
      WHERE m.table_name IN (
        'support_tickets', 'news_articles', 'courses', 'events',
        'applications', 'vacation_requests'
      )
        AND cl.link_path ~ ('/' || m.old_id::text || '(/|\?|$)')
      $q$,
      p_schema
    );
  END IF;

  FOR t IN SELECT DISTINCT table_name FROM _id_map LOOP
    EXECUTE format(
      'UPDATE %I.%I SET id = id + %s WHERE id IN (SELECT old_id FROM _id_map WHERE table_name = %L)',
      p_schema, t.table_name, staging_offset, t.table_name
    );
    EXECUTE format(
      'UPDATE %I.%I t SET id = m.new_id FROM _id_map m WHERE m.table_name = %L AND t.id = m.old_id + %s',
      p_schema, t.table_name, t.table_name, staging_offset
    );
  END LOOP;

  FOREACH tname IN ARRAY bigint_identity_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN id TYPE bigint USING id::bigint',
      p_schema, tname
    );
  END LOOP;

  FOR r IN
    SELECT
      b.table_name AS child_table,
      (regexp_match(b.def, 'FOREIGN KEY \(([a-z0-9_]+)\)'))[1] AS fk_col,
      (regexp_match(b.def, 'REFERENCES (?:[a-z_]+\.)?([a-z0-9_]+)\(id\)'))[1] AS parent_table
    FROM _fk_backup b
  LOOP
    IF r.fk_col IS NULL OR r.parent_table IS NULL THEN
      CONTINUE;
    END IF;
    IF NOT (r.parent_table = ANY (bigint_identity_tables)) THEN
      CONTINUE;
    END IF;
    EXECUTE format(
      'ALTER TABLE %I.%I ALTER COLUMN %I TYPE bigint USING %I::bigint',
      p_schema, r.child_table, r.fk_col, r.fk_col
    );
  END LOOP;

  FOR fk IN SELECT * FROM _fk_backup LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ADD CONSTRAINT %I %s',
      p_schema, fk.table_name, fk.conname, fk.def
    );
  END LOOP;

  FOR t IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_index i ON i.indrelid = c.oid AND i.indisprimary
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY (i.indkey)
    WHERE n.nspname = p_schema AND c.relkind = 'r'
    GROUP BY c.relname
    HAVING count(*) = 1
       AND min(a.attname) = 'id'
       AND min(a.atttypid) IN ('integer'::regtype, 'bigint'::regtype)
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_six_digit_id ON %I.%I', p_schema, t.relname);
    EXECUTE format('DROP TRIGGER IF EXISTS trg_four_digit_id ON %I.%I', p_schema, t.relname);
    EXECUTE format('DROP TRIGGER IF EXISTS trg_eight_digit_id ON %I.%I', p_schema, t.relname);
  END LOOP;

  FOREACH tname IN ARRAY six_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    IF seq_name IS NOT NULL THEN
      EXECUTE format('DROP SEQUENCE IF EXISTS %s', seq_name);
    END IF;

    EXECUTE format(
      'CREATE TRIGGER trg_six_digit_id BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION peru.assign_six_digit_id()',
      p_schema, tname
    );
  END LOOP;

  FOREACH tname IN ARRAY eight_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    IF seq_name IS NOT NULL THEN
      EXECUTE format('DROP SEQUENCE IF EXISTS %s', seq_name);
    END IF;

    EXECUTE format(
      'CREATE TRIGGER trg_eight_digit_id BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION peru.assign_eight_digit_id()',
      p_schema, tname
    );
  END LOOP;

  FOREACH tname IN ARRAY four_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    IF seq_name IS NOT NULL THEN
      EXECUTE format('DROP SEQUENCE IF EXISTS %s', seq_name);
    END IF;

    EXECUTE format(
      'CREATE TRIGGER trg_four_digit_id BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION peru.assign_four_digit_id()',
      p_schema, tname
    );
  END LOOP;

  FOREACH tname IN ARRAY sequential_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    SELECT a.attidentity INTO ident
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema
      AND c.relname = tname
      AND a.attname = 'id'
      AND NOT a.attisdropped;

    IF ident IS NULL OR ident = '' THEN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
      EXECUTE format(
        'ALTER TABLE %I.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        p_schema, tname
      );
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I', p_schema, tname) INTO max_id;
    IF seq_name IS NOT NULL THEN
      IF max_id < 1 THEN
        EXECUTE format('SELECT setval(%L::regclass, 1, false)', seq_name);
      ELSE
        EXECUTE format('SELECT setval(%L::regclass, %s, true)', seq_name, max_id);
      END IF;
    END IF;
  END LOOP;

  EXECUTE format(
    'GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA %I TO %I',
    p_schema, p_role
  );
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    EXECUTE format('GRANT ALL ON ALL SEQUENCES IN SCHEMA %I TO service_role', p_schema);
  END IF;
END;
$fn$;

CREATE OR REPLACE FUNCTION peru.ensure_six_digit_ids()
RETURNS void
LANGUAGE plpgsql
AS $fn$
BEGIN
  PERFORM peru.ensure_id_strategy();
END;
$fn$;

ALTER FUNCTION peru.next_six_digit_id(text) SET search_path = peru, pg_temp;
ALTER FUNCTION peru.assign_six_digit_id() SET search_path = peru, pg_temp;
ALTER FUNCTION peru.next_eight_digit_id(text) SET search_path = peru, pg_temp;
ALTER FUNCTION peru.assign_eight_digit_id() SET search_path = peru, pg_temp;
ALTER FUNCTION peru.next_four_digit_id(text) SET search_path = peru, pg_temp;
ALTER FUNCTION peru.assign_four_digit_id() SET search_path = peru, pg_temp;
ALTER FUNCTION peru.assign_ticket_reply_id() SET search_path = peru, pg_temp;
ALTER FUNCTION peru.ensure_id_strategy() SET search_path = peru, pg_temp;
ALTER FUNCTION peru.ensure_six_digit_ids() SET search_path = peru, pg_temp;

REVOKE ALL ON FUNCTION peru.next_six_digit_id(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.assign_six_digit_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.next_eight_digit_id(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.assign_eight_digit_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.next_four_digit_id(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.assign_four_digit_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.assign_ticket_reply_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.ensure_id_strategy() FROM PUBLIC;
REVOKE ALL ON FUNCTION peru.ensure_six_digit_ids() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION peru.next_six_digit_id(text) TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.assign_six_digit_id() TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.next_eight_digit_id(text) TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.assign_eight_digit_id() TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.next_four_digit_id(text) TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.assign_four_digit_id() TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.assign_ticket_reply_id() TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.ensure_id_strategy() TO intranet_peru;
GRANT EXECUTE ON FUNCTION peru.ensure_six_digit_ids() TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT EXECUTE ON FUNCTION peru.next_six_digit_id(text) TO service_role;
    GRANT EXECUTE ON FUNCTION peru.assign_six_digit_id() TO service_role;
    GRANT EXECUTE ON FUNCTION peru.next_eight_digit_id(text) TO service_role;
    GRANT EXECUTE ON FUNCTION peru.assign_eight_digit_id() TO service_role;
    GRANT EXECUTE ON FUNCTION peru.next_four_digit_id(text) TO service_role;
    GRANT EXECUTE ON FUNCTION peru.assign_four_digit_id() TO service_role;
    GRANT EXECUTE ON FUNCTION peru.assign_ticket_reply_id() TO service_role;
    GRANT EXECUTE ON FUNCTION peru.ensure_id_strategy() TO service_role;
    GRANT EXECUTE ON FUNCTION peru.ensure_six_digit_ids() TO service_role;
  END IF;
END$$;

SELECT peru.ensure_id_strategy();
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA peru TO intranet_peru;
