const db = require("../../db");

/**
 * Schema de centros de costo y del documento de identidad, idempotente al
 * arrancar (mismo patrón que vacationSchema.js y expenseSchema.js).
 *
 * Dos agrupaciones distintas conviven sobre `users` y no hay que confundirlas:
 *   - Área de trabajo: exactamente una por colaborador, columna en `users`.
 *     Define quién aprueba (el jefe del área) y qué carpeta de documentos ve.
 *   - Centro de costo: uno o dos por colaborador, tabla puente. Define a qué
 *     bolsillo se imputa el gasto. No influye en quién aprueba.
 */

const MAX_COST_CENTERS_PER_USER = 2;

const DDL_STATEMENTS = [
  // --- Documento de identidad -------------------------------------------
  // Admite NULL: los colaboradores ya cargados no lo tienen, y exigirlo aquí
  // impediría guardar cualquier ficha hasta completarlos todos. La rendición de
  // gastos sí lo exige, que es donde el dato importa de verdad.
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS national_id VARCHAR(20)`,
  // Índice único parcial: dos personas no comparten documento, pero muchas
  // pueden tenerlo vacío todavía.
  `CREATE UNIQUE INDEX IF NOT EXISTS users_national_id_unique_idx
     ON users (national_id) WHERE national_id IS NOT NULL`,

  // --- Centros de costo --------------------------------------------------
  // `code` es lo que cita contabilidad, así que es la clave natural y va único.
  `CREATE TABLE IF NOT EXISTS cost_centers (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(30) NOT NULL,
    name       VARCHAR(150) NOT NULL,
    -- Un centro en desuso se desactiva, no se borra: las rendiciones
    -- históricas tienen que seguir apuntando a algo.
    active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS cost_centers_code_unique_idx
     ON cost_centers (UPPER(TRIM(code)))`,
  `CREATE INDEX IF NOT EXISTS idx_cost_centers_active
     ON cost_centers (active) WHERE active = TRUE`,

  // --- Asignación colaborador ↔ centro de costo --------------------------
  // El tope de dos por colaborador se aplica en la ruta, no con una
  // restricción: expresarlo en SQL exige un trigger o una vista materializada,
  // y el único camino de escritura es /RRHH/centros-costo.
  `CREATE TABLE IF NOT EXISTS user_cost_centers (
    user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cost_center_id INTEGER NOT NULL REFERENCES cost_centers(id) ON DELETE CASCADE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, cost_center_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_user_cost_centers_center
     ON user_cost_centers (cost_center_id)`,

  // --- Datos heredados en la solicitud -----------------------------------
  // Una rendición es un documento contable: se congela el nombre, el documento,
  // el correo y el área tal como estaban al enviarla. Si mañana se corrige un
  // RUT o alguien cambia de área, lo ya aprobado por Finanzas no se altera.
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS requester_name VARCHAR(200)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS requester_national_id VARCHAR(20)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS requester_email VARCHAR(150)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS requester_area_name VARCHAR(150)`,

  // El FK permite filtrar y agrupar; el código y el nombre quedan congelados
  // por la misma razón que los datos del solicitante.
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS cost_center_id
     INTEGER REFERENCES cost_centers(id) ON DELETE SET NULL`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS cost_center_code VARCHAR(30)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS cost_center_name VARCHAR(150)`,
  `CREATE INDEX IF NOT EXISTS idx_expense_requests_cost_center
     ON expense_requests (cost_center_id, status)`,
];

async function ensureCostCenterSchema() {
  const client = await db.getClient();
  try {
    // Un solo round-trip: cada ALTER/CREATE por separado suma ~175ms a us-west-2.
    await client.query(DDL_STATEMENTS.join(";\n"));
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

module.exports = {
  ensureCostCenterSchema,
  MAX_COST_CENTERS_PER_USER,
  DDL_STATEMENTS,
};
