const db = require("../../db");
const { getCurrentCountry } = require("../../config/country");

/**
 * Asegura el schema del módulo de vacaciones de forma idempotente al arrancar
 * la app (mismo patrón que asegurarColumnaNoticiasDestacada en app.js).
 *
 * Este archivo ES la fuente canónica del schema: no existe carpeta migrations/
 * en el repo. Cada deployment aplica su propio DDL al arrancar contra su base.
 * Formalizar esto en migraciones versionadas está pendiente.
 *
 * IDs: vacation_requests usa 6 dígitos (trigger en schema.sql).
 * vacation_periods, vacation_balance_adjustments y public_holidays usan IDENTITY.
 */

const { HISTORY_AUDIT_ACTIONS } = require("../../constants/vacationHistory");

const AUDIT_ACTIONS_SQL = HISTORY_AUDIT_ACTIONS.map((a) => `'${a}'`).join(", ");

const DDL_STATEMENTS = [
  // users — campos laborales. El país lo fija el schema de la instancia
  // (chile / peru), no una columna por colaborador.
  `DROP INDEX IF EXISTS idx_users_employment_country`,
  `ALTER TABLE users DROP COLUMN IF EXISTS employment_country`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS hire_date DATE`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS manager_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS prior_years_credited NUMERIC(4,1) NOT NULL DEFAULT 0`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS progressive_days_override NUMERIC(4,1)`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS work_days_per_week SMALLINT NOT NULL DEFAULT 5 CHECK (work_days_per_week BETWEEN 3 AND 6)`,
  `CREATE INDEX IF NOT EXISTS idx_users_hire_date ON users (hire_date) WHERE hire_date IS NOT NULL`,

  // vacation_periods — PK IDENTITY (ensure_id_strategy convierte filas viejas)
  `CREATE TABLE IF NOT EXISTS vacation_periods (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    country_code    VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    entitled_days   NUMERIC(5,2) NOT NULL,
    used_days       NUMERIC(5,2) NOT NULL DEFAULT 0,
    adjusted_days   NUMERIC(5,2) NOT NULL DEFAULT 0,
    expires_at      DATE,
    notes           TEXT,
    protected_block_days_used NUMERIC(5,2) NOT NULL DEFAULT 0,
    flexible_block_days_used  NUMERIC(5,2) NOT NULL DEFAULT 0,
    record_met      BOOLEAN NOT NULL DEFAULT TRUE,
    record_validated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    record_notes    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, period_start)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_periods_user ON vacation_periods (user_id)`,

  // Columnas añadidas en migraciones incrementales (idempotente)
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS protected_block_days_used NUMERIC(5,2) NOT NULL DEFAULT 0`,
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS flexible_block_days_used NUMERIC(5,2) NOT NULL DEFAULT 0`,
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS record_met BOOLEAN NOT NULL DEFAULT TRUE`,
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS record_validated_by INTEGER REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS record_notes TEXT`,
  // Días gozados ANTES de la intranet, imputados a este período desde
  // vacation_history. Se mantiene separado de used_days (solicitudes de la
  // intranet) porque RRHH necesita ver las dos cifras por separado y porque
  // reimputar el historial no debe tocar lo que aprobó la intranet.
  `ALTER TABLE vacation_periods ADD COLUMN IF NOT EXISTS historical_used_days NUMERIC(5,2) NOT NULL DEFAULT 0`,

  // enum vacation_request_status (por schema: chile y peru pueden coexistir)
  `DO $$
   BEGIN
     IF NOT EXISTS (
       SELECT 1
       FROM pg_type t
       JOIN pg_namespace n ON n.oid = t.typnamespace
       WHERE t.typname = 'vacation_request_status'
         AND n.nspname = current_schema()
     ) THEN
       CREATE TYPE vacation_request_status AS ENUM ('pending','approved','rejected','cancelled','in_progress','completed');
     END IF;
   END$$`,

  // vacation_requests — PK 6 dígitos (trigger en schema.sql)
  `CREATE TABLE IF NOT EXISTS vacation_requests (
    id                 INTEGER PRIMARY KEY,
    user_id            INTEGER REFERENCES users(id) ON DELETE SET NULL,
    country_code       VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    vacation_period_id INTEGER REFERENCES vacation_periods(id) ON DELETE SET NULL,
    start_date         DATE NOT NULL,
    end_date           DATE NOT NULL,
    business_days      NUMERIC(5,2),
    calendar_days      INTEGER,
    status             vacation_request_status NOT NULL DEFAULT 'pending',
    requester_notes    TEXT,
    reviewer_notes     TEXT,
    reviewed_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at        TIMESTAMPTZ,
    fraction_ack_at    TIMESTAMPTZ,
    policy_warning_ack BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (end_date >= start_date)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_requests_user ON vacation_requests (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON vacation_requests (status)`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON vacation_requests (start_date, end_date)`,

  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS fraction_ack_at TIMESTAMPTZ`,
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS policy_warning_ack BOOLEAN NOT NULL DEFAULT FALSE`,
  // Imputaciones FIFO por período al aprobar (permite reverse completo al cancelar)
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS period_allocations JSONB`,

  // vacation_balance_adjustments (IDENTITY; ensure_id_strategy convierte filas viejas)
  `CREATE TABLE IF NOT EXISTS vacation_balance_adjustments (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacation_period_id INTEGER NOT NULL REFERENCES vacation_periods(id) ON DELETE CASCADE,
    adjusted_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
    days_delta         NUMERIC(5,2) NOT NULL,
    reason             TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_balance_adjustments_period ON vacation_balance_adjustments (vacation_period_id)`,

  // public_holidays (IDENTITY; ensure_id_strategy convierte filas viejas)
  `CREATE TABLE IF NOT EXISTS public_holidays (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code  VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    holiday_date  DATE NOT NULL,
    name          VARCHAR(200) NOT NULL,
    is_recurring  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (country_code, holiday_date)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_public_holidays_country_date ON public_holidays (country_code, holiday_date)`,

  // --- Historial anterior a la intranet -------------------------------------
  // Fuente de verdad de los días que el colaborador ya se tomó antes de que la
  // intranet administrara sus vacaciones. NO es un campo "días usados": es un
  // libro de movimientos, para poder auditarlo, corregirlo y reconstruir el
  // saldo desde cero cuando cambie la fecha de ingreso o el historial.

  // Lote de importación: permite revertir una carga completa sin tener que
  // borrar fila por fila.
  `CREATE TABLE IF NOT EXISTS vacation_history_imports (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code   VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    file_name      VARCHAR(255),
    cutoff_date    DATE,
    total_rows     INTEGER NOT NULL DEFAULT 0,
    valid_rows     INTEGER NOT NULL DEFAULT 0,
    imported_rows  INTEGER NOT NULL DEFAULT 0,
    error_rows     INTEGER NOT NULL DEFAULT 0,
    status         VARCHAR(16) NOT NULL DEFAULT 'confirmed'
                     CHECK (status IN ('confirmed', 'reverted')),
    summary        JSONB,
    created_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reverted_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
    reverted_at    TIMESTAMPTZ
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_imports_country
     ON vacation_history_imports (country_code, created_at DESC)`,

  `CREATE TABLE IF NOT EXISTS vacation_history (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    country_code    VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    period_year     INTEGER NOT NULL,
    period_month    SMALLINT CHECK (period_month BETWEEN 1 AND 12),
    start_date      DATE,
    end_date        DATE,
    days_used       NUMERIC(5,2) NOT NULL CHECK (days_used > 0),
    origin          VARCHAR(16) NOT NULL
                      CHECK (origin IN ('MANUAL', 'IMPORTED', 'ADJUSTMENT')),
    source          VARCHAR(255),
    observation     TEXT,
    cutoff_date     DATE,
    period_allocations JSONB,
    import_batch_id INTEGER REFERENCES vacation_history_imports(id) ON DELETE SET NULL,
    employee_first_name VARCHAR(150),
    employee_last_name  VARCHAR(150),
    employee_national_id VARCHAR(20),
    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ,
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_user
     ON vacation_history (user_id) WHERE deleted_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_periodo
     ON vacation_history (user_id, period_year, period_month) WHERE deleted_at IS NULL`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_batch
     ON vacation_history (import_batch_id) WHERE import_batch_id IS NOT NULL`,

  // Auditoría propia del historial: el change_log global cuenta la actividad
  // de la intranet, pero no guarda el valor anterior de cada campo.
  `CREATE TABLE IF NOT EXISTS vacation_history_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacation_history_id INTEGER,
    user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action          VARCHAR(16) NOT NULL
                      CHECK (action IN (${AUDIT_ACTIONS_SQL})),
    actor_user_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
    old_value       JSONB,
    new_value       JSONB,
    source          VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  // La bitácora también registra los datos del cálculo (ingreso, documento)
  // y los saldos de referencia. Bases ya creadas: se reemplaza el CHECK.
  `ALTER TABLE vacation_history_audit DROP CONSTRAINT IF EXISTS vacation_history_audit_action_check`,
  `ALTER TABLE vacation_history_audit ADD CONSTRAINT vacation_history_audit_action_check
     CHECK (action IN (${AUDIT_ACTIONS_SQL}))`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_audit_registro
     ON vacation_history_audit (vacation_history_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_history_audit_user
     ON vacation_history_audit (user_id, created_at DESC)`,

  // Saldo que RR.HH. tenía anotado (su Excel) a una fecha, para conciliar con
  // el que calcula la intranet. Es una referencia: no mueve el saldo.
  `CREATE TABLE IF NOT EXISTS vacation_reference_balances (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER REFERENCES users(id) ON DELETE CASCADE,
    country_code    VARCHAR(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
    as_of_date      DATE NOT NULL,
    expected_days   NUMERIC(6,2) NOT NULL,
    note            TEXT,
    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    deleted_at      TIMESTAMPTZ
  )`,
  `CREATE INDEX IF NOT EXISTS idx_vacation_reference_balances_user
     ON vacation_reference_balances (user_id, as_of_date DESC) WHERE deleted_at IS NULL`,

  // Parámetros del módulo que RRHH edita desde la intranet. Una fila por país
  // (cada schema solo tiene el suyo); la fecha de corte es única para todo el
  // país, no por trabajador.
  `CREATE TABLE IF NOT EXISTS vacation_settings (
    country_code        VARCHAR(2) PRIMARY KEY CHECK (country_code IN ('CL', 'PE')),
    history_cutoff_date DATE,
    updated_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  // --- Perú: los días no gozados ya no caducan ------------------------------
  // El motor nació con expires_at = fin de período + 365. RRHH lleva el saldo
  // acumulado sin caducidad (D.L. 713: el derecho no se extingue, la mora
  // genera indemnización), así que los períodos peruanos dejan de vencer.
  `UPDATE vacation_periods SET expires_at = NULL, updated_at = NOW()
    WHERE country_code = 'PE' AND expires_at IS NOT NULL`,

  // --- Colaborador eliminado: el historial se conserva ----------------------
  // Borrar a un colaborador no borra sus solicitudes ni sus períodos (y con
  // ellos, los ajustes de saldo): quedan con user_id NULL. La solicitud copia
  // nombre, correo y área al crearse para seguir mostrando de quién era.
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS requester_first_name VARCHAR(150)`,
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS requester_last_name VARCHAR(150)`,
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS requester_email VARCHAR(150)`,
  `ALTER TABLE vacation_requests ADD COLUMN IF NOT EXISTS requester_area_name VARCHAR(150)`,
  // Solicitudes anteriores a la copia: se completan una vez desde la ficha.
  `UPDATE vacation_requests r
      SET requester_first_name = u.first_name,
          requester_last_name  = u.last_name,
          requester_email      = u.email,
          requester_area_name  = w.area_name
     FROM users u
     LEFT JOIN work_areas w ON w.id = u.work_area_id
    WHERE u.id = r.user_id
      AND r.requester_first_name IS NULL
      AND r.requester_last_name IS NULL
      AND r.requester_email IS NULL`,
  `ALTER TABLE vacation_periods ALTER COLUMN user_id DROP NOT NULL`,
  `ALTER TABLE vacation_requests ALTER COLUMN user_id DROP NOT NULL`,
  // Sin ON DELETE (y NOT NULL) impedía borrar a quien alguna vez ajustó un saldo.
  `ALTER TABLE vacation_balance_adjustments ALTER COLUMN adjusted_by DROP NOT NULL`,
  userFkSetNull("vacation_periods", "user_id"),
  userFkSetNull("vacation_requests", "user_id"),
  userFkSetNull("vacation_balance_adjustments", "adjusted_by"),
  // El historial también sobrevive al borrado del colaborador: guarda nombre y
  // documento para que RRHH sepa de quién era al revisar una liquidación.
  userFkSetNull("vacation_history", "user_id"),
];

/**
 * DO idempotente que deja la FK de `table.column` hacia users con ON DELETE
 * SET NULL, reemplazando la que hubiera (CASCADE o sin acción) en bases ya
 * creadas. `table` y `column` son constantes de este archivo, nunca entrada.
 */
function userFkSetNull(table, column) {
  const fkQuery = `
         SELECT c.conname
           FROM pg_constraint c
           JOIN pg_class t ON t.oid = c.conrelid
           JOIN pg_namespace n ON n.oid = t.relnamespace
           JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
          WHERE c.contype = 'f'
            AND n.nspname = current_schema()
            AND t.relname = '${table}'
            AND a.attname = '${column}'`;
  return `DO $$
   DECLARE
     fk record;
   BEGIN
     FOR fk IN ${fkQuery} AND c.confdeltype <> 'n'
     LOOP
       EXECUTE format('ALTER TABLE ${table} DROP CONSTRAINT %I', fk.conname);
     END LOOP;
     IF NOT EXISTS (${fkQuery}) THEN
       ALTER TABLE ${table}
         ADD CONSTRAINT ${table}_${column}_fkey
         FOREIGN KEY (${column}) REFERENCES users(id) ON DELETE SET NULL;
     END IF;
   END$$`;
}

// Feriados legales 2025-2026 (subconjunto principal). Admin puede editar en UI.
const SEED_HOLIDAYS = [
  // Chile 2025
  ["CL", "2025-01-01", "Año Nuevo"],
  ["CL", "2025-04-18", "Viernes Santo"],
  ["CL", "2025-04-19", "Sábado Santo"],
  ["CL", "2025-05-01", "Día del Trabajo"],
  ["CL", "2025-05-21", "Día de las Glorias Navales"],
  ["CL", "2025-06-20", "Día Nacional de los Pueblos Indígenas"],
  ["CL", "2025-06-29", "San Pedro y San Pablo"],
  ["CL", "2025-07-16", "Virgen del Carmen"],
  ["CL", "2025-08-15", "Asunción de la Virgen"],
  ["CL", "2025-09-18", "Independencia Nacional"],
  ["CL", "2025-09-19", "Día de las Glorias del Ejército"],
  ["CL", "2025-10-12", "Encuentro de Dos Mundos"],
  ["CL", "2025-10-31", "Día de las Iglesias Evangélicas"],
  ["CL", "2025-11-01", "Día de Todos los Santos"],
  ["CL", "2025-12-08", "Inmaculada Concepción"],
  ["CL", "2025-12-25", "Navidad"],
  // Chile 2026
  ["CL", "2026-01-01", "Año Nuevo"],
  ["CL", "2026-04-03", "Viernes Santo"],
  ["CL", "2026-04-04", "Sábado Santo"],
  ["CL", "2026-05-01", "Día del Trabajo"],
  ["CL", "2026-05-21", "Día de las Glorias Navales"],
  ["CL", "2026-06-29", "San Pedro y San Pablo"],
  ["CL", "2026-07-16", "Virgen del Carmen"],
  ["CL", "2026-08-15", "Asunción de la Virgen"],
  ["CL", "2026-09-18", "Independencia Nacional"],
  ["CL", "2026-09-19", "Día de las Glorias del Ejército"],
  ["CL", "2026-10-12", "Encuentro de Dos Mundos"],
  ["CL", "2026-10-31", "Día de las Iglesias Evangélicas"],
  ["CL", "2026-11-01", "Día de Todos los Santos"],
  ["CL", "2026-12-08", "Inmaculada Concepción"],
  ["CL", "2026-12-25", "Navidad"],
  // Perú 2025
  ["PE", "2025-01-01", "Año Nuevo"],
  ["PE", "2025-04-17", "Jueves Santo"],
  ["PE", "2025-04-18", "Viernes Santo"],
  ["PE", "2025-05-01", "Día del Trabajo"],
  ["PE", "2025-06-29", "San Pedro y San Pablo"],
  ["PE", "2025-07-23", "Día de la Fuerza Aérea"],
  ["PE", "2025-07-28", "Fiestas Patrias"],
  ["PE", "2025-07-29", "Fiestas Patrias"],
  ["PE", "2025-08-06", "Batalla de Junín"],
  ["PE", "2025-08-30", "Santa Rosa de Lima"],
  ["PE", "2025-10-08", "Combate de Angamos"],
  ["PE", "2025-11-01", "Día de Todos los Santos"],
  ["PE", "2025-12-08", "Inmaculada Concepción"],
  ["PE", "2025-12-09", "Batalla de Ayacucho"],
  ["PE", "2025-12-25", "Navidad"],
  // Perú 2026
  ["PE", "2026-01-01", "Año Nuevo"],
  ["PE", "2026-04-02", "Jueves Santo"],
  ["PE", "2026-04-03", "Viernes Santo"],
  ["PE", "2026-05-01", "Día del Trabajo"],
  ["PE", "2026-06-29", "San Pedro y San Pablo"],
  ["PE", "2026-07-28", "Fiestas Patrias"],
  ["PE", "2026-07-29", "Fiestas Patrias"],
  ["PE", "2026-08-06", "Batalla de Junín"],
  ["PE", "2026-08-30", "Santa Rosa de Lima"],
  ["PE", "2026-10-08", "Combate de Angamos"],
  ["PE", "2026-11-01", "Día de Todos los Santos"],
  ["PE", "2026-12-08", "Inmaculada Concepción"],
  ["PE", "2026-12-09", "Batalla de Ayacucho"],
  ["PE", "2026-12-25", "Navidad"],
];

async function ensureVacationSchema() {
  const client = await db.getClient();
  try {
    // Un solo round-trip: cada ALTER/CREATE por separado suma ~175ms a us-west-2.
    await client.query(DDL_STATEMENTS.join(";\n"));
    await seedHolidays(client);
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

async function seedHolidays(client) {
  // Solo los feriados del país de esta instancia: sembrar los del otro país
  // ensucia la base con un calendario que nadie va a usar ni mantener.
  const instanceCountry = getCurrentCountry();
  const rows = SEED_HOLIDAYS.filter(([country]) => country === instanceCountry);
  if (!rows.length) return;

  const countries = rows.map(([country]) => country);
  const dates = rows.map(([, date]) => date);
  const names = rows.map(([, , name]) => name);

  await client.query(
    `INSERT INTO public_holidays (country_code, holiday_date, name)
     SELECT country_code, holiday_date, name
     FROM UNNEST($1::varchar[], $2::date[], $3::varchar[])
       AS t(country_code, holiday_date, name)
     ON CONFLICT (country_code, holiday_date) DO NOTHING`,
    [countries, dates, names],
  );
}

module.exports = { ensureVacationSchema };
