const db = require("../../db");

/**
 * Schema de letras de cambio, aplicado de forma idempotente al arrancar (mismo
 * patrón que expenseSchema.js: este archivo es la fuente canónica y
 * supabase/peru/schema.sql lo documenta).
 *
 * Un lote (bill_of_exchange_batches) es lo que se llena en el formulario: un
 * aceptante, una factura de referencia y sus condiciones. Cada letra del lote
 * es una cuota con su número, vencimiento e importe. Los datos del aceptante,
 * del aval y de la cuenta de cargo se congelan en el lote: una letra emitida
 * es un título valor y no debe cambiar si mañana el cliente se muda.
 *
 * Numeración: correlativo por año del giro (LT-00421-2026). UNIQUE sobre
 * (number_year, number_seq) es la última barrera contra dos letras con el
 * mismo número; la primera es el advisory lock de billOfExchangeService.
 */

const DDL_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS bill_of_exchange_batches (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_ref        VARCHAR(40),
    issue_date         DATE NOT NULL,
    issue_place        VARCHAR(80) NOT NULL,
    currency_code      VARCHAR(3) NOT NULL DEFAULT 'USD' CHECK (currency_code = 'USD'),
    total_amount       NUMERIC(14,2) NOT NULL CHECK (total_amount > 0),
    acceptor_name      VARCHAR(200) NOT NULL,
    acceptor_doc       VARCHAR(15) NOT NULL,
    acceptor_address   VARCHAR(300) NOT NULL,
    acceptor_locality  VARCHAR(120),
    acceptor_phone     VARCHAR(30),
    guarantor_name     VARCHAR(200),
    guarantor_doc      VARCHAR(15),
    guarantor_address  VARCHAR(300),
    guarantor_locality VARCHAR(120),
    guarantor_phone    VARCHAR(30),
    bank_name          VARCHAR(80),
    bank_office        VARCHAR(40),
    bank_account       VARCHAR(40),
    bank_dc            VARCHAR(4),
    created_by         INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  // Autocompletar el aceptante: el último lote de ese RUC/DNI.
  `CREATE INDEX IF NOT EXISTS idx_bill_batches_acceptor
     ON bill_of_exchange_batches (acceptor_doc, created_at DESC)`,

  `CREATE TABLE IF NOT EXISTS bills_of_exchange (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT NOT NULL REFERENCES bill_of_exchange_batches(id) ON DELETE CASCADE,
    installment SMALLINT NOT NULL CHECK (installment > 0),
    number_year SMALLINT NOT NULL,
    number_seq  INTEGER NOT NULL CHECK (number_seq > 0),
    due_date    DATE NOT NULL,
    amount      NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    status      VARCHAR(10) NOT NULL DEFAULT 'issued'
                CHECK (status IN ('issued','paid','voided')),
    paid_at     TIMESTAMPTZ,
    voided_at   TIMESTAMPTZ,
    void_reason VARCHAR(300),
    updated_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (number_year, number_seq),
    UNIQUE (batch_id, installment)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_bills_due
     ON bills_of_exchange (status, due_date)`,
  // Igual que el resto de tablas en supabase/peru/schema.sql: la app entra con
  // BYPASSRLS y PostgREST no ve nada sin una policy.
  "ALTER TABLE bill_of_exchange_batches ENABLE ROW LEVEL SECURITY",
  "ALTER TABLE bills_of_exchange ENABLE ROW LEVEL SECURITY",
];

async function ensureBillOfExchangeSchema() {
  await db.query(DDL_STATEMENTS.join(";\n"));
}

module.exports = { ensureBillOfExchangeSchema, DDL_STATEMENTS };
