-- Catálogo corporativo de aplicaciones, compartido por Chile y Perú.
--
-- Crear, editar o borrar una app en cualquier instancia actualiza las dos
-- páginas: chile.applications y peru.applications son vistas de esta tabla.
-- No añadir `shared` a Extra Schemas de PostgREST.
--
-- En un entorno nuevo, aplicar este archivo antes de las vistas en
-- supabase/chile/schema.sql y supabase/peru/schema.sql.

CREATE SCHEMA IF NOT EXISTS shared;

REVOKE ALL ON SCHEMA shared FROM PUBLIC;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON SCHEMA shared FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON SCHEMA shared FROM authenticated;
  END IF;
END$$;

GRANT USAGE ON SCHEMA shared TO intranet_chile, intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT USAGE ON SCHEMA shared TO service_role;
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS shared.applications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(255) NOT NULL,
  description text,
  url_pc text,
  url_apk text,
  qr_ios text,
  qr_apk text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  changelog text,
  notified boolean DEFAULT true,
  icon_url text,
  url_ios text,
  url_web text,
  -- 'corporate' alimenta la vista Apps; 'support' la autoayuda de Soporte.
  catalog character varying(20) NOT NULL DEFAULT 'corporate',
  -- Orden manual dentro del catálogo; NULL conserva el orden por fecha.
  sort_order integer,
  CONSTRAINT applications_catalog_check CHECK (catalog IN ('corporate', 'support'))
);

CREATE INDEX IF NOT EXISTS idx_applications_catalog ON shared.applications (catalog);
CREATE INDEX IF NOT EXISTS idx_applications_catalog_orden ON shared.applications (catalog, sort_order);

-- Si Chile todavía tiene tabla propia, es la fuente (ids y archivos).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    INSERT INTO shared.applications (
      id, name, description, url_pc, url_apk, qr_ios, qr_apk,
      created_at, updated_at, changelog, notified, icon_url, url_ios, url_web,
      catalog, sort_order
    )
    OVERRIDING SYSTEM VALUE
    SELECT
      src.id, src.name, src.description, src.url_pc, src.url_apk, src.qr_ios, src.qr_apk,
      src.created_at, src.updated_at, src.changelog, src.notified, src.icon_url,
      src.url_ios, src.url_web, src.catalog, src.sort_order
    FROM chile.applications src
    WHERE NOT EXISTS (
      SELECT 1 FROM shared.applications dst WHERE dst.id = src.id
    );
  END IF;
END$$;

SELECT setval(
  pg_get_serial_sequence('shared.applications', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM shared.applications), 1), 1),
  true
);

ALTER TABLE shared.applications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS dashboard_all ON shared.applications';
  EXECUTE 'CREATE POLICY dashboard_all ON shared.applications FOR ALL TO postgres USING (true) WITH CHECK (true)';
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'DROP POLICY IF EXISTS deny_postgrest ON shared.applications';
    EXECUTE 'CREATE POLICY deny_postgrest ON shared.applications FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)';
  END IF;
END$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON shared.applications TO intranet_chile, intranet_peru;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA shared TO intranet_chile, intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON TABLE shared.applications TO service_role;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA shared TO service_role;
  END IF;
END$$;

ALTER DEFAULT PRIVILEGES IN SCHEMA shared
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO intranet_chile, intranet_peru;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO intranet_chile, intranet_peru;

-- Chile y Perú ven el mismo catálogo a través de search_path.
CREATE SCHEMA IF NOT EXISTS chile;
CREATE SCHEMA IF NOT EXISTS peru;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'v'
  ) THEN
    DROP VIEW chile.applications;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    DROP TABLE chile.applications CASCADE;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'applications' AND c.relkind = 'v'
  ) THEN
    DROP VIEW peru.applications;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    DROP TABLE peru.applications CASCADE;
  END IF;
END$$;
CREATE OR REPLACE VIEW chile.applications
  WITH (security_invoker = true) AS
  SELECT * FROM shared.applications;
GRANT SELECT, INSERT, UPDATE, DELETE ON chile.applications TO intranet_chile;

CREATE OR REPLACE VIEW peru.applications
  WITH (security_invoker = true) AS
  SELECT * FROM shared.applications;
GRANT SELECT, INSERT, UPDATE, DELETE ON peru.applications TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON chile.applications TO service_role;
    GRANT ALL ON peru.applications TO service_role;
  END IF;
END$$;
