-- Catálogo corporativo de aplicaciones, compartido por Chile y Perú.
--
-- Crear, editar o borrar una app en cualquier instancia actualiza las dos
-- páginas: chile.applications y peru.applications son vistas de esta tabla.
-- No añadir `shared` a Extra Schemas de PostgREST.
--
-- En un entorno nuevo, aplicar este archivo antes de las vistas en
-- supabase/chile/schema.sql y supabase/peru/schema.sql.

CREATE SCHEMA IF NOT EXISTS shared;

REVOKE ALL ON SCHEMA shared FROM PUBLIC;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON SCHEMA shared FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON SCHEMA shared FROM authenticated;
  END IF;
END$$;

GRANT USAGE ON SCHEMA shared TO intranet_chile, intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT USAGE ON SCHEMA shared TO service_role;
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS shared.applications (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(255) NOT NULL,
  description text,
  url_pc text,
  url_apk text,
  qr_ios text,
  qr_apk text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  changelog text,
  notified boolean DEFAULT true,
  icon_url text,
  url_ios text,
  url_web text,
  -- 'corporate' alimenta la vista Apps; 'support' la autoayuda de Soporte.
  catalog character varying(20) NOT NULL DEFAULT 'corporate',
  -- Orden manual dentro del catálogo; NULL conserva el orden por fecha.
  sort_order integer,
  CONSTRAINT applications_catalog_check CHECK (catalog IN ('corporate', 'support'))
);

CREATE INDEX IF NOT EXISTS idx_applications_catalog ON shared.applications (catalog);
CREATE INDEX IF NOT EXISTS idx_applications_catalog_orden ON shared.applications (catalog, sort_order);

-- Si Chile todavía tiene tabla propia, es la fuente (ids y archivos).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    INSERT INTO shared.applications (
      id, name, description, url_pc, url_apk, qr_ios, qr_apk,
      created_at, updated_at, changelog, notified, icon_url, url_ios, url_web,
      catalog, sort_order
    )
    OVERRIDING SYSTEM VALUE
    SELECT
      src.id, src.name, src.description, src.url_pc, src.url_apk, src.qr_ios, src.qr_apk,
      src.created_at, src.updated_at, src.changelog, src.notified, src.icon_url,
      src.url_ios, src.url_web, src.catalog, src.sort_order
    FROM chile.applications src
    WHERE NOT EXISTS (
      SELECT 1 FROM shared.applications dst WHERE dst.id = src.id
    );
  END IF;
END$$;

SELECT setval(
  pg_get_serial_sequence('shared.applications', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM shared.applications), 1), 1),
  true
);

ALTER TABLE shared.applications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS dashboard_all ON shared.applications';
  EXECUTE 'CREATE POLICY dashboard_all ON shared.applications FOR ALL TO postgres USING (true) WITH CHECK (true)';
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'DROP POLICY IF EXISTS deny_postgrest ON shared.applications';
    EXECUTE 'CREATE POLICY deny_postgrest ON shared.applications FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)';
  END IF;
END$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON shared.applications TO intranet_chile, intranet_peru;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA shared TO intranet_chile, intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON TABLE shared.applications TO service_role;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA shared TO service_role;
  END IF;
END$$;

ALTER DEFAULT PRIVILEGES IN SCHEMA shared
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO intranet_chile, intranet_peru;
ALTER DEFAULT PRIVILEGES IN SCHEMA shared
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO intranet_chile, intranet_peru;

-- Chile y Perú ven el mismo catálogo a través de search_path.
CREATE SCHEMA IF NOT EXISTS chile;
CREATE SCHEMA IF NOT EXISTS peru;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'v'
  ) THEN
    DROP VIEW chile.applications;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    DROP TABLE chile.applications CASCADE;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'applications' AND c.relkind = 'v'
  ) THEN
    DROP VIEW peru.applications;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'applications' AND c.relkind = 'r'
  ) THEN
    DROP TABLE peru.applications CASCADE;
  END IF;
END$$;
CREATE OR REPLACE VIEW chile.applications
  WITH (security_invoker = true) AS
  SELECT * FROM shared.applications;
GRANT SELECT, INSERT, UPDATE, DELETE ON chile.applications TO intranet_chile;

CREATE OR REPLACE VIEW peru.applications
  WITH (security_invoker = true) AS
  SELECT * FROM shared.applications;
GRANT SELECT, INSERT, UPDATE, DELETE ON peru.applications TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON chile.applications TO service_role;
    GRANT ALL ON peru.applications TO service_role;
  END IF;
END$$;

-- Galería de eventos, compartida por Chile y Perú.
--
-- Un evento público se ve en las dos intranets. Uno privado solo en la del
-- país que lo creó (country_code). chile.events y peru.events filtran eso;
-- Home, el detalle y el asistente siguen leyendo `events`.
-- Las fotos quedan en el bucket del país que las sube: no se duplican.

CREATE TABLE IF NOT EXISTS shared.events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(200) NOT NULL,
  slug character varying(200) NOT NULL UNIQUE,
  description text,
  image text,
  created_at timestamp without time zone DEFAULT now(),
  -- Columna histórica de Chile. El asistente la consulta; Perú no la tenía.
  fecha text,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  is_private boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_events_country_private
  ON shared.events (country_code, is_private);

-- Copia lo que todavía viva en tablas de país. Los id nuevos no importan:
-- la URL es el slug y nadie referencia events.id. Si el slug choca, el de
-- Perú pasa a {slug}-pe y sus objetos del bucket intranet-content-pe se
-- renombran para no mezclar fotos con las de Chile.
DO $$
DECLARE
  rec record;
  new_slug text;
  suffix integer;
  image_value text;
  old_prefix text;
  new_prefix text;
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'events' AND c.relkind = 'r'
  ) THEN
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'chile' AND table_name = 'events' AND column_name = 'fecha'
    ) THEN
      INSERT INTO shared.events (
        name, slug, description, image, created_at, fecha, country_code, is_private
      )
      SELECT
        src.name, src.slug, src.description, src.image, src.created_at, src.fecha,
        'CL', false
      FROM chile.events src
      WHERE NOT EXISTS (
        SELECT 1 FROM shared.events dst WHERE dst.slug = src.slug
      );
    ELSE
      INSERT INTO shared.events (
        name, slug, description, image, created_at, fecha, country_code, is_private
      )
      SELECT
        src.name, src.slug, src.description, src.image, src.created_at, NULL,
        'CL', false
      FROM chile.events src
      WHERE NOT EXISTS (
        SELECT 1 FROM shared.events dst WHERE dst.slug = src.slug
      );
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'events' AND c.relkind = 'r'
  ) THEN
    FOR rec IN SELECT * FROM peru.events ORDER BY id LOOP
      IF EXISTS (
        SELECT 1 FROM shared.events dst
        WHERE dst.country_code = 'PE'
          AND dst.name = rec.name
          AND dst.created_at IS NOT DISTINCT FROM rec.created_at
      ) THEN
        CONTINUE;
      END IF;

      new_slug := rec.slug;
      IF EXISTS (SELECT 1 FROM shared.events dst WHERE dst.slug = new_slug) THEN
        new_slug := rec.slug || '-pe';
        suffix := 2;
        WHILE EXISTS (SELECT 1 FROM shared.events dst WHERE dst.slug = new_slug) LOOP
          new_slug := rec.slug || '-pe-' || suffix;
          suffix := suffix + 1;
        END LOOP;
      END IF;

      image_value := rec.image;
      IF new_slug IS DISTINCT FROM rec.slug THEN
        old_prefix := 'eventos/' || rec.slug;
        new_prefix := 'eventos/' || new_slug;
        IF image_value IS NOT NULL THEN
          image_value := replace(image_value, old_prefix || '/', new_prefix || '/');
        END IF;

        IF to_regclass('storage.objects') IS NOT NULL THEN
          BEGIN
            UPDATE storage.objects
            SET name = new_prefix || substring(name FROM char_length(old_prefix) + 1)
            WHERE bucket_id = 'intranet-content-pe'
              AND (
                name = old_prefix
                OR left(name, char_length(old_prefix || '/')) = old_prefix || '/'
              );
          EXCEPTION
            WHEN insufficient_privilege OR undefined_table THEN
              RAISE NOTICE 'No se renombraron archivos de %: %', old_prefix, SQLERRM;
          END;
        END IF;
      END IF;

      INSERT INTO shared.events (
        name, slug, description, image, created_at, fecha, country_code, is_private
      )
      VALUES (
        rec.name, new_slug, rec.description, image_value, rec.created_at, NULL,
        'PE', false
      );
    END LOOP;
  END IF;
END$$;

SELECT setval(
  pg_get_serial_sequence('shared.events', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM shared.events), 1), 1),
  true
);

ALTER TABLE shared.events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS dashboard_all ON shared.events';
  EXECUTE 'CREATE POLICY dashboard_all ON shared.events FOR ALL TO postgres USING (true) WITH CHECK (true)';
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
     AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    EXECUTE 'DROP POLICY IF EXISTS deny_postgrest ON shared.events';
    EXECUTE 'CREATE POLICY deny_postgrest ON shared.events FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)';
  END IF;
END$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON shared.events TO intranet_chile, intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON TABLE shared.events TO service_role;
  END IF;
END$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'events' AND c.relkind = 'v'
  ) THEN
    DROP VIEW chile.events;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relname = 'events' AND c.relkind = 'r'
  ) THEN
    DROP TABLE chile.events CASCADE;
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'events' AND c.relkind = 'v'
  ) THEN
    DROP VIEW peru.events;
  ELSIF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'peru' AND c.relname = 'events' AND c.relkind = 'r'
  ) THEN
    DROP TABLE peru.events CASCADE;
  END IF;
END$$;

CREATE OR REPLACE VIEW chile.events
  WITH (security_invoker = true) AS
  SELECT * FROM shared.events
  WHERE is_private = false OR country_code = 'CL'
  WITH CHECK OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON chile.events TO intranet_chile;

CREATE OR REPLACE VIEW peru.events
  WITH (security_invoker = true) AS
  SELECT * FROM shared.events
  WHERE is_private = false OR country_code = 'PE'
  WITH CHECK OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON peru.events TO intranet_peru;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT ALL ON chile.events TO service_role;
    GRANT ALL ON peru.events TO service_role;
  END IF;
END$$;
