const db = require("../../db");
const logger = require("../../utils/logger");
const { getCountryConfig, getCurrentCountry } = require("../../config/country");
const { areaSlug } = require("../../constants/workAreas");
const { banksForCountry } = require("../../constants/banks");

/**
 * Schema del centro de gastos, aplicado de forma idempotente al arrancar
 * (mismo patrón que vacationSchema.js: este archivo ES la fuente canónica,
 * no existe carpeta migrations/ en el repo).
 *
 * Cubre tres piezas que se estrenan juntas y están acopladas:
 *   1. work_areas.manager_user_id — el jefe de área, requisito para aprobar.
 *   2. documents.work_area_id / doc_kind — carpetas ligadas al área real en
 *      vez del slug hardcodeado que vivía en routes/procesos.js.
 *   3. expense_requests y sus tablas hijas.
 *
 * IDs: expense_requests usa 6 dígitos, reutilizando assign_six_digit_id()
 * (definida en supabase/<pais>/schema.sql).
 */

const DDL_STATEMENTS = [
  // --- Jefe de área -------------------------------------------------------
  // ON DELETE SET NULL y no CASCADE: dar de baja al jefe no debe llevarse el
  // área por delante, sólo dejarla sin jefatura (y con eso, sin poder rendir).
  `ALTER TABLE work_areas ADD COLUMN IF NOT EXISTS manager_user_id
     INTEGER REFERENCES users(id) ON DELETE SET NULL`,
  `CREATE INDEX IF NOT EXISTS idx_work_areas_manager
     ON work_areas (manager_user_id) WHERE manager_user_id IS NOT NULL`,

  // --- Carpetas de procedimientos y protocolos por área real --------------
  // CASCADE: borrar un área borra sus filas de documents. Los objetos del
  // bucket los borra a mano la ruta de eliminación (Storage no tiene FK).
  `ALTER TABLE documents ADD COLUMN IF NOT EXISTS work_area_id
     INTEGER REFERENCES work_areas(id) ON DELETE CASCADE`,
  `ALTER TABLE documents ADD COLUMN IF NOT EXISTS doc_kind VARCHAR(20)`,
  `CREATE INDEX IF NOT EXISTS idx_documents_area_kind
     ON documents (work_area_id, doc_kind)`,

  // --- Enums (por schema: chile y peru coexisten en la misma base) --------
  `DO $$
   BEGIN
     IF NOT EXISTS (
       SELECT 1 FROM pg_type t
       JOIN pg_namespace n ON n.oid = t.typnamespace
       WHERE t.typname = 'expense_request_kind' AND n.nspname = current_schema()
     ) THEN
       CREATE TYPE expense_request_kind AS ENUM ('rendicion','fondos');
     END IF;
   END$$`,
  `DO $$
   BEGIN
     IF NOT EXISTS (
       SELECT 1 FROM pg_type t
       JOIN pg_namespace n ON n.oid = t.typnamespace
       WHERE t.typname = 'expense_request_status' AND n.nspname = current_schema()
     ) THEN
       CREATE TYPE expense_request_status AS ENUM
         ('pending','approved_manager','approved_finance','rejected','cancelled','draft');
     END IF;
   END$$`,

  // --- expense_requests — PK de 6 dígitos ---------------------------------
  // work_area_id se congela al crear: si mañana el colaborador cambia de área,
  // la solicitud sigue perteneciendo al área que la aprobó.
  `CREATE TABLE IF NOT EXISTS expense_requests (
    id                  INTEGER PRIMARY KEY,
    kind                expense_request_kind   NOT NULL,
    status              expense_request_status NOT NULL DEFAULT 'pending',
    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    work_area_id        INTEGER REFERENCES work_areas(id) ON DELETE SET NULL,
    title               VARCHAR(200) NOT NULL,
    description         TEXT,
    currency_code       VARCHAR(3) NOT NULL,
    total_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
    needed_by           DATE,
    manager_user_id     INTEGER REFERENCES users(id) ON DELETE SET NULL,
    manager_reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    manager_reviewed_at TIMESTAMPTZ,
    manager_notes       TEXT,
    finance_reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    finance_reviewed_at TIMESTAMPTZ,
    finance_notes       TEXT,
    rejected_stage      VARCHAR(10),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_expense_requests_user
     ON expense_requests (user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_expense_requests_status
     ON expense_requests (status, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_expense_requests_area
     ON expense_requests (work_area_id, status)`,
  // Bandeja del jefe: "lo que me toca aprobar" es este índice.
  `CREATE INDEX IF NOT EXISTS idx_expense_requests_manager
     ON expense_requests (manager_user_id, status)
     WHERE manager_user_id IS NOT NULL`,

  `CREATE TABLE IF NOT EXISTS expense_request_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES expense_requests(id) ON DELETE CASCADE,
    item_date  DATE,
    detail     VARCHAR(300) NOT NULL,
    amount     NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
    sort_order SMALLINT NOT NULL DEFAULT 0
  )`,
  `CREATE INDEX IF NOT EXISTS idx_expense_items_request
     ON expense_request_items (request_id, sort_order)`,
  // Una línea de borrador puede no tener monto todavía. Enviar lo exige
  // (normalizeItems), así que en una solicitud enviada nunca es NULL.
  `ALTER TABLE expense_request_items ALTER COLUMN amount DROP NOT NULL`,

  `CREATE TABLE IF NOT EXISTS expense_request_attachments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES expense_requests(id) ON DELETE CASCADE,
    name       VARCHAR(200) NOT NULL,
    url        TEXT NOT NULL,
    public_id  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_expense_attachments_request
     ON expense_request_attachments (request_id)`,

  // --- Categoría y días por línea ------------------------------------------
  // Admiten NULL por las líneas anteriores a la categoría; las nuevas las exige
  // expenseRequestService.normalizeItems. Los días sólo aplican a hospedaje.
  `ALTER TABLE expense_request_items ADD COLUMN IF NOT EXISTS category VARCHAR(30)`,
  `ALTER TABLE expense_request_items ADD COLUMN IF NOT EXISTS days SMALLINT
     CHECK (days IS NULL OR days > 0)`,

  // --- Datos bancarios -----------------------------------------------------
  // PK = código SBIF: es el identificador que citan las nóminas de pago.
  // Un banco que desaparece se desactiva: las solicitudes lo siguen citando.
  `CREATE TABLE IF NOT EXISTS banks (
    code        VARCHAR(3) PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE
  )`,

  // Cuentas propias guardadas para futuras solicitudes. La clave es la cuenta
  // misma: no hay id que exponer y guardar dos veces la misma no la duplica.
  `CREATE TABLE IF NOT EXISTS user_bank_accounts (
    user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_code      VARCHAR(3) NOT NULL REFERENCES banks(code) ON UPDATE CASCADE,
    account_type   VARCHAR(20) NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at   TIMESTAMPTZ,
    PRIMARY KEY (user_id, bank_code, account_type, account_number)
  )`,

  // Cuenta de destino congelada en la solicitud, igual que el solicitante: si
  // mañana el colaborador borra o cambia su cuenta, lo que Finanzas transfirió
  // sigue registrado. El titular son los requester_* (sólo cuentas propias).
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS bank_code
     VARCHAR(3) REFERENCES banks(code) ON UPDATE CASCADE`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS bank_name VARCHAR(120)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS bank_account_type VARCHAR(20)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(20)`,

  // --- Encabezado de la planilla -------------------------------------------
  // NULL en las solicitudes anteriores; las nuevas los exige createRequest
  // (salvo el destino, que no aplica a pagos directos).
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS fund_type VARCHAR(10)
     CHECK (fund_type IS NULL OR fund_type IN ('fijo', 'rendir'))`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS destination VARCHAR(150)`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS period_start DATE`,
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS period_end DATE`,
  // Fondo asignado de una rendición. NULL = sin fondo (compra con dinero
  // propio). El saldo a reintegrar no se guarda: es total_amount - esto.
  `ALTER TABLE expense_requests ADD COLUMN IF NOT EXISTS assigned_amount NUMERIC(14,2)
     CHECK (assigned_amount IS NULL OR assigned_amount >= 0)`,

  // ID de 6 dígitos reutilizando la función ya instalada por schema.sql.
  `DO $$
   BEGIN
     IF EXISTS (
       SELECT 1 FROM pg_proc p
       JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE p.proname = 'assign_six_digit_id' AND n.nspname = current_schema()
     ) THEN
       DROP TRIGGER IF EXISTS trg_six_digit_id ON expense_requests;
       CREATE TRIGGER trg_six_digit_id
         BEFORE INSERT ON expense_requests
         FOR EACH ROW EXECUTE FUNCTION assign_six_digit_id();
     END IF;
   END$$`,
];

/** Tipos de carpeta que viven en `documents`. */
const DOC_KINDS = ["procedimiento", "protocolo"];

/**
 * Backfill de las carpetas legacy.
 *
 * Hasta ahora `documents.type` era un string compuesto ('procedimiento_logistica')
 * contra una lista de áreas hardcodeada que no existía en work_areas. Se resuelve
 * cada slug contra el área real y se rellenan work_area_id + doc_kind.
 *
 * Los slugs sin área correspondiente (contabilidad, comercial...) quedan con
 * work_area_id NULL a propósito: no se pierden, se muestran en la carpeta
 * "Sin área" que sólo ven los administradores.
 */
async function backfillDocumentAreas(client) {
  const { rows: pending } = await client.query(
    `SELECT DISTINCT type
       FROM documents
      WHERE work_area_id IS NULL
        AND split_part(type, '_', 1) = ANY($1::text[])
        AND position('_' in type) > 0`,
    [DOC_KINDS],
  );
  if (!pending.length) return 0;

  const { rows: areas } = await client.query(
    "SELECT id, area_name FROM work_areas",
  );
  const areaBySlug = new Map(areas.map((a) => [areaSlug(a.area_name), a.id]));

  const legacyTypes = [];
  const areaIds = [];
  const kinds = [];

  for (const { type } of pending) {
    const separator = String(type).indexOf("_");
    if (separator < 0) continue;
    const kind = String(type).slice(0, separator);
    const slug = String(type).slice(separator + 1);
    if (!DOC_KINDS.includes(kind)) continue;
    const areaId = areaBySlug.get(slug);
    if (!areaId) continue;
    legacyTypes.push(type);
    areaIds.push(areaId);
    kinds.push(kind);
  }

  if (!legacyTypes.length) return 0;

  const { rowCount } = await client.query(
    `UPDATE documents d
        SET work_area_id = m.area_id,
            doc_kind     = m.kind
       FROM UNNEST($1::text[], $2::int[], $3::text[]) AS m(legacy_type, area_id, kind)
      WHERE d.type = m.legacy_type
        AND d.work_area_id IS NULL`,
    [legacyTypes, areaIds, kinds],
  );
  return rowCount;
}

/**
 * Rellena doc_kind en toda fila que no lo tenga, incluidas las huérfanas.
 *
 * Cubre dos casos que el backfill por área no toca: los slugs cuya área no
 * existe ("procedimiento_contabilidad") y los tipos sin sufijo alguno
 * ("procedimiento" a secas, que sí existe en la base). Sin doc_kind esas filas
 * no aparecerían en ninguna carpeta, ni siquiera en la de "Sin área".
 */
async function backfillDocKind(client) {
  await client.query(
    `UPDATE documents
        SET doc_kind = split_part(type, '_', 1)
      WHERE doc_kind IS NULL
        AND split_part(type, '_', 1) = ANY($1::text[])`,
    [DOC_KINDS],
  );
}

/**
 * Siembra el catálogo de bancos del país de la instancia.
 *
 * Actualiza nombre y tipo si cambiaron en constants/banks.js, pero no toca
 * `active`: desactivar un banco es una decisión que se toma en la base.
 */
async function seedBanks(client) {
  const banks = banksForCountry(getCurrentCountry());
  if (!banks.length) return;
  await client.query(
    `INSERT INTO banks (code, name, entity_type)
     SELECT c, n, t FROM UNNEST($1::text[], $2::text[], $3::text[]) AS s(c, n, t)
     ON CONFLICT (code) DO UPDATE
       SET name = EXCLUDED.name, entity_type = EXCLUDED.entity_type`,
    [banks.map((b) => b.code), banks.map((b) => b.name), banks.map((b) => b.entityType)],
  );
}

async function ensureExpenseSchema() {
  const client = await db.getClient();
  try {
    // Un solo round-trip: cada ALTER/CREATE por separado suma ~175ms a us-west-2.
    await client.query(DDL_STATEMENTS.join(";\n"));
    // Bases creadas antes de los borradores. Va sola y fuera del lote: un valor
    // nuevo de un enum no puede usarse en la misma transacción que lo agrega.
    await client.query("ALTER TYPE expense_request_status ADD VALUE IF NOT EXISTS 'draft'");
    // Después del ALTER: el predicado usa el valor nuevo. Lo recorre el job que
    // elimina los borradores caducados.
    await client.query(
      `CREATE INDEX IF NOT EXISTS idx_expense_requests_drafts
         ON expense_requests (updated_at) WHERE status = 'draft'`,
    );
    await seedBanks(client);
    const migrated = await backfillDocumentAreas(client);
    await backfillDocKind(client);
    if (migrated > 0) {
      logger.info("gastos", `${migrated} documento(s) ligados a su área`);
    }
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

/** Código de moneda con el que nacen las solicitudes de esta instancia. */
function currentCurrencyCode() {
  return getCountryConfig().currency.code;
}

module.exports = {
  ensureExpenseSchema,
  currentCurrencyCode,
  DOC_KINDS,
  DDL_STATEMENTS,
};
